[book]
title = "MetaMystia文档"
description = "MetaMystia是为游戏《东方夜雀食堂》所开发的联机Mod，本网站它的文档站。"
authors = ["AnYiEE", "MetaMikuAI"]
language = "zh-CN"

[output.html]
additional-css = ["assets/fancybox/fancybox.css", "custom.css"]
additional-js = [
  "assets/search/fzf.umd.js",
  "assets/search/elasticlunr.js",
  "assets/fancybox/fancybox.umd.js",
  "assets/js/fingerprintjs-v4.6.2.js",
  "custom.js",
]
mathjax-support = true
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/MetaMikuAI/MetaMystia"
edit-url-template = "https://github.com/AnYiEE/meta-mystia-doc/edit/master/{path}"

[output.html.playground]
line-numbers = true
runnable = false

[output.html.print]
enable = false
